### ISSUE TITLE
Traductions fr manquantes

### ISSUE THREAD

**Issue by fjg** [sgmap/mrs#23]
- <img width="320" alt="capture d ecran 2017-12-19 a 11 47 11" src="https://user-images.githubusercontent.com/91435/34153485-862e83c4-e4b2-11e7-8820-aecc5df1f58a.png">
- <img width="261" alt="capture d ecran 2017-12-19 a 11 47 23" src="https://user-images.githubusercontent.com/91435/34153486-86709764-e4b2-11e7-894e-7d7f71ca1b1d.png">
- <img width="301" alt="capture d ecran 2017-12-19 a 11 47 29" src="https://user-images.githubusercontent.com/91435/34153487-86cc293a-e4b2-11e7-84a0-6a368f4bd519.png">
-

**Comment by jpic** [comment]
Fixé en 2a574932587d5c9a579449f217137445a1ca3523
