### ISSUE TITLE
Upload d’image sur android ne fonctionne pas avec la prise de photo

### ISSUE THREAD

**Issue by notmoebius** [sgmap/mrs#33]
Lors de l’upload sous android avec staging.mrs, une image provenant de la galerie, c’est ok. Si j’effectueune prise de photo, ça bloque:

![2b6d5ce1-7b1f-4df3-9ae4-522b0c0ce865](https://user-images.githubusercontent.com/32330644/34318858-bdf3589e-e7d1-11e7-8a1a-613dfd194229.jpeg)

**Comment by jpic** [comment]
Est-ce-que ça marche en attendant d'abord la fin des uploads pour soumettre le formulaire ?

**Comment by notmoebius** [comment]
L'image ci-dessus est une capture après plusieurs minutes. L'upload bloque si je prend une photo avec le capteur photo. Si c'est une image de la galerie, cela fonctionne : tu verras d'ailleurs une image jpeg en ligne avec l'action remove.
Le contexte: je clique sur le bouton fichier puis il me permet de choisir soit la galerie de photos, soit d'utiliser l'appareil photo. si j’utilise l'appareil photo, la photo bloque sur l'upload  comme tu peux le voir sur la capture. Idem pour ios mais il ne matérialise pas l'avancement de l'upload.

**Comment by jpic** [comment]
Salut Brice, est-ce-que c'est toujours le cas avec le nouveau script d'upload utilisé sur https://jpic.mrs.yourlabs.org ?

**Comment by notmoebius** [comment]
C’est un bug différent: erreur http 2/413.

**Comment by jpic** [comment]
Merci pour le détail j'ai pu reproduire ;)

**Comment by jpic** [comment]
C'est bon pour moi en staging.
