### ISSUE TITLE
staging.mrs landing page revoir la mise en page

### ISSUE THREAD

**Issue by notmoebius** [sgmap/mrs#34]
Revoir l'indentation et la justification du texte.

![landing page](https://user-images.githubusercontent.com/32330644/34319031-a0d0c6d4-e7d6-11e7-9dca-699a829c4a02.png)

Modèle d'agencement à reprendre:
![mrs beta](https://user-images.githubusercontent.com/32330644/34319047-f25e3c98-e7d6-11e7-92c8-d8410e33b16c.png)

**Comment by jpic** [comment]
@tbinetruy 4 u <3

**Comment by jpic** [comment]
Fixé en staging !

![2017-12-29-011634_336x800_scrot](https://user-images.githubusercontent.com/94636/34427371-c63fbf0a-ec41-11e7-9c5b-7e89e7a4ae87.png)
