### ISSUE TITLE
Comportement bouton ajout de fichier #11

### ISSUE THREAD

**Issue by notmoebius** [sgmap/mrs#37]
US issue #11 
Lors de l'ajout d'un fichier puis le retrait avec l'action "remove" (à mettre en Fr d'ailleurs), le champ n'est pas remis à RAZ mais garde le nom de l'ancien fichier uploadé.
![image](https://user-images.githubusercontent.com/32330644/34321967-c44b48ba-e81b-11e7-916d-b04f66391648.png)

**Comment by jpic** [comment]
Salut Brice, est-ce-que c'est toujours le cas avec le nouveau script d'upload utilisé sur https://jpic.mrs.yourlabs.org ?

**Comment by notmoebius** [comment]
Oui, si ce n’est qu’il affiche Effacer au lieu de remote.

**Comment by jpic** [comment]
Ca n'est plus le cas pour moi en staging, peux tu me confirmer et eventuellement fermer l'issuer stp ? Merci ;)

![2017-12-28-160016_980x313_scrot](https://user-images.githubusercontent.com/94636/34414217-4a4eab12-ebe8-11e7-85a3-ca52569d3e15.png)
