### ISSUE TITLE
Calendrier date de naissance #11

### ISSUE THREAD

**Issue by notmoebius** [sgmap/mrs#38]
US issue #11 : 
la saisie de la date de naissance est au format US.
le widget calendrier est en Us (December au mieu de Décembre).
En revanche, l'affichage est en Fr c'est à dire DD/MM/YYYY.
Proposition mettre en Fr DD/MM/YYYY partout.

**Comment by jpic** [comment]
Bonjour,

Les dates sont elles au bon format ? J'ajoute le LocaleMiddleware qu'il manquait dans un commit mais je crois que c'est le commit qui activait la locale française qui s'en est chargé, peux-tu me confirmer stp ? N'hésites pas à fermer l'issue si c'est bon pour toi ;)

![2017-12-28-151338_272x113_scrot](https://user-images.githubusercontent.com/94636/34413144-c6d3a8ec-ebe1-11e7-9f34-5774b4c1ef33.png)


Merci

**Comment by jpic** [comment]
Fixé en staging <3

**Comment by notmoebius** [comment]
Hello, le format de date est OK mais si l'on doit mettre le formalisme en prod ou pré-prod, il faudrait je pense mettre le calendrier en FR.
https://innovcpam31.slack.com/files/U75HALGAJ/F8M5KKAER/image.png
