### ISSUE TITLE
Libellé bouton "FICHIER" issue #11

### ISSUE THREAD

**Issue by notmoebius** [sgmap/mrs#39]
Mettre un libellé plus  explicite : au lieu de fichier mettre "Ajouter votre PMT".
Sur l'autre bouton des PJ, mettre "Ajouter vos justificatifs".

Est-ce possible ?

**Comment by jpic** [comment]
C'est possible, je l'ai mise en placeholder de l'input à droite du dit bouton, si cette proposition te vas n'hésites pas à fermer l'issue ;)

**Comment by jpic** [comment]
Un correctif rend le champs plus explicite est déployé en staging.
