### ISSUE TITLE
Contrôle de cohérence des dates issue#11

### ISSUE THREAD

**Issue by notmoebius** [sgmap/mrs#40]
Le formulaire doit-être invalidé si date aller et > date retour.
Lors de la saisie, la saisie de la date aller du trajet, la date retour doit être au moins être supérieure ou égale à la date de trajet aller.

Après test, j'ai pu saisir une date de retour antérieure à la date aller: pas cohérent.

**Comment by jpic** [comment]
Fixé en staging <3
