### ISSUE TITLE
Date de naissance postérieure à la date du jour issue #11

### ISSUE THREAD

**Issue by notmoebius** [sgmap/mrs#42]
Dans le formulaire, il manque quelques contrôle comme la date de naissance qui doit être < à la date du jour. 
![image](https://user-images.githubusercontent.com/32330644/34323067-0e18a89e-e839-11e7-802f-60e1c4cccfd2.png)

**Comment by jpic** [comment]
![2017-12-28-161543_607x141_scrot](https://user-images.githubusercontent.com/94636/34414572-668f24ee-ebea-11e7-9731-5b343e20c8ec.png)
