### ISSUE TITLE
Contrôle des champs date et montant en € à faire

### ISSUE THREAD

**Issue by notmoebius** [sgmap/mrs#55]
Deux points de contrôle à voir:
- si la date du trajet retour est vide, par défaut, il prend la valeur de date du trajet aller
- si le montant est négatif, pas de message d'alerte mais le form n'est pas soumis

A voir: https://innovcpam31.slack.com/files/U75HALGAJ/F8LG54NEM/image.png

**Comment by jpic** [comment]
Merci, n'hésites pas à créer deux issues différentes la prochaine fois ;)
