### ISSUE TITLE
Erreur intitulé "hier" / "aujourd'hui"

### ISSUE THREAD

**Issue by Natacha1974** [sgmap/mrs#58]
Il faut modifier les intitulés "aujourd'hui" / "demain" en "hier" / "aujourd'hui"

**Comment by Johan1983** [comment]
Il s'agit des intitulés présents dans le pavé "Une semaine pour être remboursé"

**Comment by Johan1983** [comment]
![e3c2b43c-737d-43aa-a278-624f10b9b9a7](https://user-images.githubusercontent.com/34479425/34561404-16f34266-f14a-11e7-9cdf-2e3336f1e5da.png)

**Comment by notmoebius** [comment]
Je viens de le corriger dans le commit cf1b093942ecb3f6267dc6b97841bfae2df14c51
