### ISSUE TITLE
Intitulé formulaire rbt champ NIR

### ISSUE THREAD

**Issue by Johan1983** [sgmap/mrs#61]
L’info bulle concernant le champ NiR n’est pas compréhensible : il indique une formulaire lorsque le nir depasse le nombre de caracteres requis.
Cf capture
![305293b8-a68c-43e6-954e-39beb8b6ed52](https://user-images.githubusercontent.com/34479425/34561306-aa110ef8-f149-11e7-89ef-8c6f6f698adb.jpeg)

**Comment by fjg** [comment]
Il faudrait rajouter un contrôle sur le NIR pour respecter son format cf. https://github.com/sgmap/mrs/wiki/Acronymes.

Pour démarrer, contrôle sur uniquement la longueur (13 digits) et caractères 0-9, pas plus à ce stade.

**Comment by jpic** [comment]
Combien de caractères minimums ? 13 aussi ?

**Comment by fjg** [comment]
Oui toujours sur 13 chiffres. Regarde la construction dans le wiki.
(il y a 2 chiffres en plus sur les cartes secu, mais c'est une clé calculable via un algo. On ne la demande donc pas aux assurés)
