### ISSUE TITLE
En tant que équipe MRS, je peux consulter les demandes de remboursement des assurés

### ISSUE THREAD

**Issue by fjg** [sgmap/mrs#7]
Je peux me **connecter** sur MRS avec mon compte.

Je peux voir la liste des demandes des assurés, les champs affichés seront

* NIR (numéro assuré ex: 1XXXXXXXXXXXX)
* Montant
* Adresse mail

Je peux cliquer sur une demande particulière et voir l'ensemble des informations fournies par l'assurée :

* voir les justificatifs
* ...

**Comment by fjg** [comment]
Un NIR c'est le numér AMELI...

**Comment by jpic** [comment]
Fermeture de l'issue de test
