### ISSUE TITLE
Importer les images du site dans le projet

### ISSUE THREAD

**Issue by fjg** [sgmap/mrs#9]
Ne pas charger les images depuis Cloudinary ex: https://res.cloudinary.com/hrscywv4p/image/upload/c_limit,fl_lossy,h_1500,w_2000,f_auto,q_auto/v1/1251740/logo-incubateur-avec-titre_rnoq0u.png

**Comment by jpic** [comment]
Les télecharger dans src/mrs/static pour les servir via staticfiles ;)

**Comment by fjg** [comment]
Il y a encore les images des icônes 1/2/3 

* https://assets.strikingly.com/static/icons/flat-modern/04.png
* https://assets.strikingly.com/static/icons/flat-circle-160/135.png
* https://assets.strikingly.com/static/icons/flat-circle-160/26.png
* https://res.cloudinary.com/hrscywv4p/image/upload/c_limit,fl_lossy,h_9000,w_1200,f_auto,q_auto/v1/1251740/c874e665e60d4174abdde90ed42c780c_skjjoy.png
* ...

Ne plus dépendre de ressources externes.

**Comment by jpic** [comment]
Fixé en staging
